import type { Metadata } from "next";
import { ArrowDownRight } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { ButtonLink } from "@/components/ui/button";
import { Reveal } from "@/components/motion/reveal";
import { SectionHeading } from "@/components/section-heading";
import { CtaSection } from "@/components/cta-section";
import { process, services } from "@/lib/site-data";

export const metadata: Metadata = { title: "Services", description: "AI, software engineering, enterprise platforms, cloud, cyber security, data engineering, QA, managed support, and engineering talent.", alternates: { canonical: "/services" } };

export default function ServicesPage() {
  return <><PageHero eyebrow="Capabilities" title="Engineering across the full technology lifecycle." copy="Strategy when the direction is unclear. Delivery when the path is demanding. Specialist depth when your team needs more leverage."><div className="flex flex-col gap-3 sm:flex-row"><ButtonLink href="#service-catalog" size="lg">Explore capabilities</ButtonLink><ButtonLink href="/contact" variant="secondary" size="lg">Discuss a challenge</ButtonLink></div></PageHero>
  <section id="service-catalog" className="pb-20 sm:pb-28"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><div className="border-t border-white/10">{services.map((service, index) => { const Icon = service.icon; return <Reveal key={service.slug}><article id={service.slug} className="grid scroll-mt-28 gap-8 border-b border-white/10 py-12 sm:py-16 lg:grid-cols-[.42fr_1fr] lg:gap-20"><div><div className="flex items-center gap-4"><span className="font-mono text-xs text-slate-600">0{index + 1}</span><div className="grid size-11 place-items-center rounded-xl border border-white/10 bg-white/[.03] text-cyan-200"><Icon className="size-5" strokeWidth={1.6} /></div></div><h2 className="mt-7 max-w-sm font-display text-3xl font-medium tracking-[-.05em] text-white sm:text-4xl">{service.title}</h2></div><div><p className="max-w-2xl text-lg leading-8 text-slate-300">{service.short}</p><ul className="mt-8 grid gap-x-8 gap-y-1 sm:grid-cols-2">{service.capabilities.map((capability) => <li key={capability} className="flex min-h-11 items-center gap-3 border-b border-white/[.07] py-2 text-sm text-slate-400"><ArrowDownRight className="size-3.5 shrink-0 text-blue-300" aria-hidden="true" />{capability}</li>)}</ul></div></article></Reveal>; })}</div></div></section>
  <section className="section-shell border-y border-white/10 bg-[#070a11]"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Reveal><SectionHeading eyebrow="Delivery process" title="A disciplined path from uncertainty to operation." copy="Each engagement is adapted to the work, but the principles remain stable: align early, reduce risk visibly, and build for what comes after launch." /></Reveal><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{process.map((step, index) => { const Icon = step.icon; return <Reveal key={step.title} delay={index * .06}><article className="h-full rounded-[1.4rem] border border-white/10 bg-white/[.025] p-6"><div className="flex items-center justify-between"><Icon className="size-5 text-cyan-200" strokeWidth={1.6} /><span className="font-mono text-[10px] text-slate-600">0{index + 1}</span></div><h3 className="mt-12 font-display text-2xl font-medium text-white">{step.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{step.copy}</p></article></Reveal>; })}</div></div></section><CtaSection title="The challenge can be complex. The next step should be clear." copy="Tell us where the system, product, or team needs to move. We’ll help shape the right path." /></>;
}
