import type { Metadata } from "next";
import { Check, Clock3, Globe2, Layers3, UsersRound } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { ButtonLink } from "@/components/ui/button";
import { Reveal } from "@/components/motion/reveal";
import { SectionHeading } from "@/components/section-heading";
import { CtaSection } from "@/components/cta-section";
import { talentGroups } from "@/lib/site-data";

export const metadata: Metadata = { title: "Engineering Talent", description: "Dedicated developers, project teams, and staff augmentation across software, AI, data, cloud, security, QA, design, and delivery.", alternates: { canonical: "/talent" } };

const models = [
  { icon: UsersRound, title: "Dedicated specialists", copy: "Add a focused capability to an existing team with clear ownership and direct collaboration." },
  { icon: Layers3, title: "Complete project teams", copy: "A balanced unit spanning architecture, engineering, quality, product, and delivery leadership." },
  { icon: Clock3, title: "Flexible augmentation", copy: "Scale capacity around roadmaps, migrations, launches, or hard-to-hire specialist roles." },
];

export default function TalentPage() {
  return <><PageHero eyebrow="Engineering talent" title="The capability you need. Integrated into the way you work." copy="Experienced specialists and complete teams who bring more than capacity—they bring judgment, ownership, and engineering discipline."><div className="flex flex-col gap-3 sm:flex-row"><ButtonLink href="/contact" size="lg" arrow>Build your team</ButtonLink><ButtonLink href="#skill-matrix" variant="secondary" size="lg">View skill matrix</ButtonLink></div></PageHero>
  <section className="section-shell border-y border-white/10 bg-[#070a11]"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Reveal><SectionHeading eyebrow="Engagement models" title="Scale with intent, not just headcount." copy="Every model includes deliberate onboarding, defined responsibilities, transparent communication, and regular delivery feedback." /></Reveal><div className="mt-14 grid gap-4 lg:grid-cols-3">{models.map((model, index) => { const Icon = model.icon; return <Reveal key={model.title} delay={index * .06}><article className="h-full min-h-72 rounded-[1.5rem] border border-white/10 bg-white/[.025] p-7"><Icon className="size-6 text-cyan-200" strokeWidth={1.5} /><h3 className="mt-16 font-display text-2xl font-medium tracking-[-.04em] text-white">{model.title}</h3><p className="mt-4 text-sm leading-7 text-slate-400">{model.copy}</p></article></Reveal>; })}</div></div></section>
  <section id="skill-matrix" className="section-shell"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Reveal><SectionHeading eyebrow="Skill matrix" title="Specialists across product and platform delivery." copy="Roles can be engaged individually or composed into a multidisciplinary team around a defined outcome." /></Reveal><div className="mt-14 border-t border-white/10">{talentGroups.map((group, index) => <Reveal key={group.title}><div className="grid gap-6 border-b border-white/10 py-9 lg:grid-cols-[.34fr_1fr]"><div className="flex items-start gap-4"><span className="font-mono text-[10px] text-slate-600">0{index + 1}</span><h3 className="font-display text-xl font-medium text-white">{group.title}</h3></div><div className="flex flex-wrap gap-2">{group.roles.map((role) => <span key={role} className="inline-flex min-h-10 items-center rounded-full border border-white/10 bg-white/[.025] px-4 text-xs text-slate-300">{role}</span>)}</div></div></Reveal>)}</div></div></section>
  <section className="section-shell border-y border-white/10 bg-white/[.012]"><div className="mx-auto grid max-w-[1240px] gap-14 px-5 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:gap-24"><Reveal><SectionHeading eyebrow="Delivery modes" title="Built around your working reality." copy="Remote, hybrid, and onsite options adapt to collaboration needs, security posture, and geography." /><div className="mt-8 flex items-center gap-3 text-sm text-slate-300"><Globe2 className="size-5 text-cyan-200" />Distributed by default. Connected by design.</div></Reveal><Reveal delay={.08}><ul className="grid gap-3 sm:grid-cols-2">{["Role and outcome definition", "Technical and collaboration assessment", "Structured team onboarding", "Shared tools and delivery cadence", "Performance and continuity reviews", "Flexible scale-up or transition"].map((item) => <li key={item} className="flex min-h-16 items-center gap-3 rounded-xl border border-white/10 bg-white/[.025] px-4 text-sm text-slate-300"><Check className="size-4 shrink-0 text-cyan-300" />{item}</li>)}</ul></Reveal></div></section><CtaSection title="Add the team your roadmap is waiting for." copy="Tell us the roles, capability gaps, and operating context. We’ll shape a focused team model around them." /></>;
}
