import type { Metadata } from "next";
import { Aperture, Compass, Eye, Scale } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { ButtonLink } from "@/components/ui/button";
import { Reveal } from "@/components/motion/reveal";
import { SectionHeading } from "@/components/section-heading";
import { CtaSection } from "@/components/cta-section";
import { values } from "@/lib/site-data";

export const metadata: Metadata = { title: "About", description: "Infinity DataLabs is an AI engineering, software, and technology resource partner focused on clarity, trust, and accountable execution.", alternates: { canonical: "/about" } };

const foundations = [
  { icon: Compass, label: "Mission", title: "Make advanced technology useful, dependable, and easier to evolve.", copy: "We help organizations turn ambitious ideas and difficult systems into practical capability." },
  { icon: Eye, label: "Vision", title: "A future where intelligent systems amplify good teams—not complicate them.", copy: "Technology should improve decisions, operations, and experiences while earning trust at every layer." },
];

export default function AboutPage() {
  return <><PageHero eyebrow="About Infinity" title="Technology partnership, measured by what endures." copy="Infinity DataLabs brings together AI engineering, software delivery, and specialist talent to help organizations build with confidence."><ButtonLink href="/contact" size="lg" arrow>Work with us</ButtonLink></PageHero>
  <section className="section-shell border-y border-white/10 bg-[#070a11]"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><div className="grid gap-4 lg:grid-cols-2">{foundations.map((item, index) => { const Icon = item.icon; return <Reveal key={item.label} delay={index * .07}><article className="h-full min-h-[390px] rounded-[1.75rem] border border-white/10 bg-white/[.025] p-7 sm:p-10"><div className="flex items-center gap-3"><Icon className="size-5 text-cyan-200" strokeWidth={1.6} /><span className="eyebrow">{item.label}</span></div><h2 className="mt-20 max-w-xl font-display text-3xl font-medium tracking-[-.055em] text-white sm:text-4xl">{item.title}</h2><p className="mt-5 max-w-lg text-sm leading-7 text-slate-400">{item.copy}</p></article></Reveal>; })}</div></div></section>
  <section id="philosophy" className="section-shell"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Reveal><SectionHeading eyebrow="Working philosophy" title="Senior thinking should stay close to the work." copy="We structure teams to reduce translation layers. The people making important technical decisions remain connected to implementation, testing, and operation." /></Reveal><div className="mt-16 grid gap-14 lg:grid-cols-[.72fr_1.28fr] lg:gap-24"><Reveal><div className="sticky top-28 overflow-hidden rounded-[1.5rem] border border-white/10 bg-[#080d16] p-7"><div className="hero-grid absolute inset-0 opacity-30" /><Aperture className="relative size-8 text-cyan-200" strokeWidth={1.4} /><p className="relative mt-24 font-display text-3xl font-medium tracking-[-.05em] text-white">Innovation is only valuable when it improves the system around it.</p><div className="relative mt-8 h-px bg-gradient-to-r from-cyan-300/50 via-blue-500/30 to-transparent" /></div></Reveal><div className="border-t border-white/10">{values.map((value, index) => <Reveal key={value.title}><article className="grid gap-4 border-b border-white/10 py-8 sm:grid-cols-[60px_1fr]"><span className="font-mono text-[10px] text-slate-600">0{index + 1}</span><div><h3 className="font-display text-2xl font-medium tracking-[-.04em] text-white">{value.title}</h3><p className="mt-3 max-w-xl text-sm leading-7 text-slate-400">{value.copy}</p></div></article></Reveal>)}</div></div></div></section>
  <section className="section-shell border-y border-white/10 bg-white/[.012]"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Reveal><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="eyebrow">Leadership principles</p><h2 className="mt-5 font-display text-4xl font-medium tracking-[-.055em] text-white sm:text-5xl">Direction without distance.</h2></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-6"><Scale className="size-5 text-cyan-200" /><h3 className="mt-8 font-display text-xl text-white">Responsible judgment</h3><p className="mt-3 text-sm leading-6 text-slate-400">Technical ambition balanced with business context, security, and long-term stewardship.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.025] p-6"><Aperture className="size-5 text-violet-300" /><h3 className="mt-8 font-display text-xl text-white">Visible execution</h3><p className="mt-3 text-sm leading-6 text-slate-400">Clear progress, direct communication, and decisions made with the people closest to the evidence.</p></div></div></div></Reveal></div></section><CtaSection title="Strong partnerships start with a clear conversation." copy="If the work matters and the path is demanding, we’d like to hear about it." /></>;
}
