import { ArrowDown, Check, MoveRight } from "lucide-react";
import { ButtonLink } from "@/components/ui/button";
import { InfinityNebula } from "@/components/infinity-nebula";
import { Reveal } from "@/components/motion/reveal";
import { SectionHeading } from "@/components/section-heading";
import { ServiceCard } from "@/components/service-card";
import { Stats } from "@/components/stats";
import { TechMarquee } from "@/components/tech-marquee";
import { CtaSection } from "@/components/cta-section";
import { engagementModels, industries, process, services } from "@/lib/site-data";

export default function HomePage() {
  return <>
    <section className="relative min-h-[900px] overflow-hidden pb-24 pt-36 sm:pt-44 lg:flex lg:min-h-screen lg:items-center lg:pt-28">
      <div className="hero-grid absolute inset-0 opacity-45" aria-hidden="true" /><div className="hero-orb-a absolute left-[18%] top-[16%] size-[340px] rounded-full bg-cyan-400/[.045] blur-[100px]" aria-hidden="true" /><div className="hero-orb-b absolute right-[12%] top-[20%] size-[460px] rounded-full bg-violet-600/[.06] blur-[130px]" aria-hidden="true" />
      <div className="relative mx-auto grid w-full max-w-[1240px] grid-cols-1 items-center gap-16 px-5 sm:px-8 lg:grid-cols-[1.08fr_.92fr] lg:gap-12">
        <Reveal delay={0.12} duration={1.05} y={30}><div className="inline-flex min-h-9 items-center gap-2 rounded-full border border-cyan-200/15 bg-cyan-200/[.04] px-3 font-mono text-[10px] uppercase tracking-[.16em] text-cyan-100"><span className="relative flex size-1.5"><span className="absolute inline-flex size-full animate-ping rounded-full bg-cyan-300 opacity-45" /><span className="relative inline-flex size-1.5 rounded-full bg-cyan-300 shadow-[0_0_12px_#58e6ff]" /></span>AI-first technology partner</div><h1 className="mt-8 max-w-4xl text-balance font-display text-[clamp(3.55rem,7.4vw,7.35rem)] font-medium leading-[.88] tracking-[-.075em]"><span className="display-gradient">Engineering</span><br /><span className="text-white">intelligent systems.</span></h1><p className="mt-8 max-w-xl text-pretty text-lg leading-8 text-slate-300 sm:text-xl">We build AI products, scalable software, and high-performing engineering teams for organizations moving beyond the expected.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><ButtonLink href="/services" size="lg" arrow>Explore services</ButtonLink><ButtonLink href="/contact" variant="secondary" size="lg">Talk to experts</ButtonLink></div><a href="#expertise" className="mt-12 inline-flex min-h-11 items-center gap-3 text-xs font-medium uppercase tracking-[.16em] text-slate-500 transition-colors hover:text-slate-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300"><ArrowDown className="size-4" />Discover our approach</a></Reveal>
        <div className="mx-auto min-w-0 w-full max-w-[620px]"><InfinityNebula /></div>
      </div>
    </section>

    <section className="border-y border-white/10 bg-white/[.012]"><div className="mx-auto flex max-w-[1240px] flex-col gap-5 px-5 py-6 text-xs uppercase tracking-[.15em] text-slate-500 sm:px-8 lg:flex-row lg:items-center lg:justify-between"><span>Built for complex environments</span><div className="flex flex-wrap gap-x-7 gap-y-3 text-slate-300"><span>Enterprise</span><span>Government</span><span>Mid-market</span><span>Startups</span></div></div></section>

    <section id="expertise" className="section-shell"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Reveal><div className="flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><SectionHeading eyebrow="Connected expertise" title="One partner across the systems that matter." copy="From model behavior to production infrastructure, we connect the disciplines required to build technology that holds up in the real world." /><ButtonLink href="/services" variant="secondary" arrow>All services</ButtonLink></div></Reveal><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.slice(0, 6).map((service, index) => <Reveal key={service.slug} delay={(index % 3) * 0.06}><ServiceCard service={service} index={index} /></Reveal>)}</div></div></section>

    <section className="section-shell border-y border-white/10 bg-[#070a11]"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-24"><Reveal><SectionHeading eyebrow="Why Infinity" title="Engineering depth without organizational drag." copy="We bring senior thinking close to delivery. Fewer handoffs, clearer decisions, and a team designed around the work—not a fixed catalog." /></Reveal><Reveal delay={0.08}><div className="grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-2">{["Architecture grounded in operating reality", "AI safety and evaluation built into delivery", "Security and quality embedded from day one", "Direct access to the people doing the work"].map((item) => <div key={item} className="flex min-h-32 gap-3 bg-[#080c14] p-6"><Check className="mt-0.5 size-5 shrink-0 text-cyan-300" aria-hidden="true" /><p className="text-sm leading-6 text-slate-300">{item}</p></div>)}</div></Reveal></div><div className="mt-20"><Stats /></div></div></section>

    <section className="section-shell"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Reveal><SectionHeading eyebrow="Industry contexts" title="Different pressures. The same demand for dependable systems." /></Reveal><div className="mt-14 grid gap-px overflow-hidden rounded-[1.75rem] border border-white/10 bg-white/10 lg:grid-cols-2">{industries.map((industry, index) => <Reveal key={industry.title} delay={index * .04}><article className="group min-h-64 bg-[#070a10] p-7 transition-colors hover:bg-[#0a0e17] sm:p-9"><div className="flex items-center justify-between"><span className="font-mono text-[10px] tracking-[.16em] text-slate-600">0{index + 1}</span><MoveRight className="size-4 text-slate-600 transition-transform group-hover:translate-x-1 group-hover:text-cyan-300" aria-hidden="true" /></div><h3 className="mt-16 font-display text-3xl font-medium tracking-[-.05em] text-white">{industry.title}</h3><p className="mt-4 max-w-md text-sm leading-7 text-slate-400">{industry.copy}</p></article></Reveal>)}</div></div></section>

    <section className="section-shell overflow-hidden border-y border-white/10 bg-white/[.012]"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Reveal><SectionHeading eyebrow="Technology ecosystem" title="Modern choices. Proven foundations." copy="We select technology for fit, maintainability, and operating context—not for novelty." /></Reveal></div><div className="mt-14"><TechMarquee /></div></section>

    <section className="section-shell"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Reveal><SectionHeading eyebrow="Flexible engagement" title="The right shape for the work ahead." copy="Engage Infinity DataLabs as a technology partner, an engineering partner, or a seamless extension of your team." /></Reveal><div className="mt-14 grid gap-4 md:grid-cols-2">{engagementModels.map((model, index) => <Reveal key={model.title} delay={(index % 2) * .06}><article className="relative min-h-64 overflow-hidden rounded-[1.5rem] border border-white/10 bg-white/[.025] p-7 sm:p-9"><span className="font-mono text-xs text-cyan-200/70">{model.number}</span><h3 className="mt-12 font-display text-3xl font-medium tracking-[-.05em] text-white">{model.title}</h3><p className="mt-4 max-w-lg text-sm leading-7 text-slate-400">{model.copy}</p></article></Reveal>)}</div></div></section>

    <section className="section-shell border-y border-white/10 bg-[#070a11]"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Reveal><SectionHeading eyebrow="How we work" title="Progress you can see. Decisions you can trust." /></Reveal><div className="relative mt-16 grid gap-10 md:grid-cols-2 lg:grid-cols-4"><div className="absolute left-0 right-0 top-6 hidden h-px bg-gradient-to-r from-transparent via-blue-400/40 to-transparent lg:block" aria-hidden="true" />{process.map((step, index) => { const Icon = step.icon; return <Reveal key={step.title} delay={index * .07}><article className="relative"><div className="grid size-12 place-items-center rounded-full border border-blue-300/25 bg-[#0b1220] text-cyan-200 shadow-[0_0_0_7px_#070a11]"><Icon className="size-4" strokeWidth={1.7} /></div><p className="mt-8 font-mono text-[10px] tracking-[.15em] text-slate-600">0{index + 1}</p><h3 className="mt-3 font-display text-2xl font-medium tracking-tight text-white">{step.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{step.copy}</p></article></Reveal>; })}</div></div></section>
    <CtaSection />
  </>;
}
